### ISSUE TITLE
Multiple tasks in a set

### ISSUE THREAD

**Issue by jbroudou** [mhlavac/gearman#4]
In the client how does one submit a set with multiple tasks? 

I recall forking this library when it was hosted at Publero/net_gearman to allow public access to create a set and then manually adding the task to that set before calling runSet().

I wanted to check before doing that again.

**Comment by mhlavac** [comment]
Julian, I'm sorry not to get back to you. This library is not maintained anymore and I'm closing all the issues as they are outdated.
