### ISSUE TITLE
Composer PHAR in project repo

### ISSUE THREAD

**Issue by samlikins** [mhlavac/gearman#8]
The `composer.phar` application should not be a part of the project, and should be removed.

Leaving the application in the project creates two primary issues:
1. It increases the project size by over 1MB
2. The composer application will have to be updated each time it's checked out

To make sure the file does not get included again:
- Perform a `git rm composer.phar` command
- Add `composer.phar` to the `.gitignore` file
- Make sure to commit and push

This will leave the composer application in the directory, but force `git` to ignore it.

**Comment by mhlavac** [comment]
@samlikins thank you for reporting this. The composer.phar was removed in master. I plan to tag new version soon.

I would like to add more automated tests to make it easier to test out changes done by contributors.
